[features]
seeds = false
skip-lint = false

[programs.mainnet]
resonance_protocol = "RWcZBKQyd5rryLD8dfrMZ8imgtfqTfpGZi4gKGS8j7N"

[programs.devnet]
resonance_protocol = "RWcZBKQyd5rryLD8dfrMZ8imgtfqTfpGZi4gKGS8j7N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.mainnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
